import { Certification, ExperiencePost, Project } from "./types";

export const projectsData: Project[] = [
  {
    id: 1,
    title: "Lumi",
    description:
      "WhatsApp AI-powered customer support automation using Meta and GPT APIs for e-commerce clients.",
    demo_url: "https://lumiapp.mx/",
    github_url: "",
    technologies: [
      "Python",
      "Django",
      "OpenAI",
      "Meta API",
      "Celery",
      "Redis",
      "DRF",
      "Docker",
      "Azure Platform",
    ],
    download_url: null,
    featured: true,
    start_date: null,
    end_date: null,
    live_site: true,
    details: null,
  },
  {
    id: 2,
    title: "Flight Booking Platform",
    description:
      "Revamped UX for Betterseat's flight booking platform with intelligent seat selection algorithms.",
    demo_url: "https://www.betterseat.ai/",
    github_url: "",
    technologies: [
      "Django",
      "Tailwind CSS",
      "Playwright",
      "PostgresSQL",
      "Docker",
      "ProxyProvider",
      "Linux",
      "MacOS",
    ],
    download_url: null,
    featured: true,
    start_date: null,
    end_date: null,
    live_site: true,
    details: null,
  },
  {
    id: 3,
    title: "Personal Portfolio v1",
    description:
      "Portfolio website built with HTML, Javascript and CSS",
    demo_url: "",
    github_url: "",
    technologies: ["JavaScript", "HTML", "CSS", "Linux"],
    download_url: null,
    featured: false,
    start_date: null,
    end_date: null,
    live_site: true,
    details: null,
  },
  {
    id: 4,
    title: "Portfolio v2 (This site)",
    description:
      "Modern portfolio website built with Next.js 15, featuring space theme and smooth animations.",
    demo_url: "https://www.sebastianfrausto.com/",
    github_url: "",
    technologies: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
    ],
    download_url: null,
    featured: true,
    start_date: null,
    end_date: null,
    live_site: true,
    details: null,
  },
  {
    id: 5,
    title: "Flutter E-commerce App",
    description:
      "A cross-platform mobile app designed to optimize cargo transportation by efficiently managing truck and freight vehicle capacity. Key features include: PDF Generation – Create invoices, reports, and shipping documents on the go. Attendance & Load Tracking (CRUD Operations) – Monitor cargo vehicles to maximize trip efficiency by filling unused space. Dual-App Integration: Carrier and Client apps.",
    demo_url: "",
    github_url: "",
    technologies: ["Flutter", "GraphQL", "Ruby on rails"],
    download_url: null,
    featured: false,
    start_date: null,
    end_date: null,
    live_site: false,
    details: null,
  },
  {
    id: 6,
    title: "Crochet Business Management App",
    description:
      "Crochet biz app: Tracks finances & material use. Optimizes costs & inventory for amigurumi makers. Simple tool for handmade businesses.",
    demo_url: "",
    github_url: "",
    technologies: [
      "Flutter",
      "Isardb package",
      "flutter_secure_storage",
      "RFID and NFC",
    ],
    download_url: null,
    featured: false,
    start_date: null,
    end_date: null,
    live_site: false,
    details: null,
  },
  {
    id: 7,
    title: "Sweet Chores",
    description:
      "A lightweight TO-DO app with Google Auth and cloud sync, built for seamless task management.",
    demo_url: "",
    github_url: "https://github.com/sebaszap123-dev/sweet_chores",
    technologies: [
      "Flutter",
      "Firebase",
      "Google Auth",
      "Google Drive API",
      "Google Cloud Storage",
    ],
    download_url: null,
    featured: false,
    start_date: null,
    end_date: null,
    live_site: false,
    details: null,
  },
  {
    id: 8,
    title: "Monopoly Banker App",
    description:
      "Practice Flutter app for NFC to read Monopoly bank cards; educational and non-commercial.",
    demo_url: "",
    github_url: "https://github.com/sebaszap123-dev/monopoly-banker-nfc",
    technologies: ["Flutter", "NFC", "Android", "Android Studio", "C++"],
    download_url:
      "https://drive.google.com/file/d/1UJsrIwzfwgv1LJ9hNEm4f7O4poCl6Joy/view",
    featured: false,
    start_date: null,
    end_date: null,
    live_site: false,
    details: null,
  },
];

export const experiencesData: ExperiencePost[] = [
  {
    id: 1,
    title: "Backend Developer",
    company: "Smarttie",
    description:
      "Architect and lead developer for a custom Retrieval-Augmented Generation (RAG) system and backend services.",
    start_date: "Oct 2023",
    end_date: null,
    is_current: true,
    employment_type: "Full-time",
    technologies: {
      achievements: [
        "Designed RAG architecture with semantic search using pgvector",
        "Built message processing with Celery and Redis for AI assistants",
        "Implemented Azure Functions for serverless invoice processing",
        "Migrated legacy SQL to SQLAlchemy + Alembic with versioning",
        "Developed REST APIs for auth, notifications and Azure integrations",
      ],
      technologies: [
        "Python",
        "Django",
        "DRF",
        "Celery",
        "Redis",
        "pgvector",
        "SQLAlchemy",
        "Alembic",
        "Azure Functions",
        "Docker",
        "Next.js",
      ],
    },
  },
  {
    id: 2,
    title: "Full-Stack Developer",
    company: "Betterseat (Remote)",
    description:
      "Re-engineered UX for flight seat reservation platform, improving onboarding and dashboards; implemented preference algorithms and tests.",
    start_date: "Mar 2024",
    end_date: "May 2025",
    is_current: false,
    employment_type: "Contract",
    technologies: {
      achievements: [
        "Redesigned landing, onboarding and dashboard flows",
        "Implemented user seat preference algorithms",
        "Added end-to-end tests",
      ],
      technologies: [
        "Django",
        "Tailwind CSS",
        "Playwright",
        "PostgreSQL",
        "Docker",
      ],
    },
  },
  {
    id: 3,
    title: "AI Training Specialist",
    company: "Outlier (Remote)",
    description:
      "Trained and refined AI models through real coding challenges and prompt engineering; ensured correctness of AI-generated code.",
    start_date: "Dec 2023",
    end_date: "Apr 2025",
    is_current: false,
    employment_type: "Contract",
    technologies: {
      achievements: [
        "Designed complex prompts to improve code generation",
        "Debugged and fixed functional issues in AI outputs",
      ],
      technologies: ["Python", "TypeScript", "Prompt Engineering"],
    },
  },
  {
    id: 4,
    title: "Flutter Developer",
    company: "Freeway Company",
    description:
      "Developed Flutter apps with reusable widgets; integrated PDF generation with Python and GraphQL services.",
    start_date: "May 2022",
    end_date: "Jul 2023",
    is_current: false,
    employment_type: "Full-time",
    technologies: {
      achievements: [
        "Built reusable UI components for consistent UX",
        "Integrated Python/GraphQL PDF generators",
      ],
      technologies: ["Flutter", "Dart", "GraphQL", "Python"],
    },
  },
];

export const certificationsData: Certification[] = [
  {
    id: 1,
    title: "EnglishScore Core Skills (CEFR B1)",
    issuer: "British Council",
    issue_date: "Nov 2023",
    expiration_date: "",
    credential_id: null,
    credential_url: null,
  },
  {
    id: 2,
    title: "DevOps Professional",
    issuer: "IBM via Coursera",
    issue_date: "Jun 2024",
    expiration_date: "",
    credential_id: null,
    credential_url: null,
  },
  {
    id: 3,
    title: "Cloud Computing Specialist",
    issuer: "IBM via Coursera",
    issue_date: "Jul 2024",
    expiration_date: "",
    credential_id: null,
    credential_url: null,
  },
  {
    id: 4,
    title: "Agile Development and Scrum Practitioner",
    issuer: "IBM via Coursera",
    issue_date: "Jul 2024",
    expiration_date: "",
    credential_id: null,
    credential_url: null,
  },
];


